import turtle
turtle.speed('fastest')


for contador in range(4):
	turtle.forward(40)
	turtle.left(90)
	turtle.forward(40)
	turtle.left(90)
	turtle.forward(40)
	turtle.left(90)
	turtle.forward(40)
	turtle.left(90)
	turtle.forward(40)
	for contador in range(8%2==0):
		turtle.color('black')
		turtle.begin_fill()
		turtle.forward(40)
		turtle.left(90)
		turtle.forward(40)
		turtle.left(90)
		turtle.forward(40)
		turtle.left(90)
		turtle.forward(40)
		turtle.left(90)
		turtle.forward(40)
		turtle.end_fill()
turtle.right(90)
turtle.forward(40)
turtle.right(90)
for contador in range(4):
	turtle.forward(40)
	turtle.right(90)
	turtle.forward(40)
	turtle.right(90)
	turtle.forward(40)
	turtle.right(90)
	turtle.forward(40)
	turtle.right(90)
	turtle.forward(40)
	for contador in range(8%2==0):
		turtle.color('black')
		turtle.begin_fill()
		turtle.forward(40)
		turtle.right(90)
		turtle.forward(40)
		turtle.right(90)
		turtle.forward(40)
		turtle.right(90)
		turtle.forward(40)
		turtle.right(90)
		turtle.forward(40)
		turtle.end_fill()
turtle.left(90)
turtle.forward(40)
turtle.left(90)
for contador in range(4):
	turtle.forward(40)
	turtle.left(90)
	turtle.forward(40)
	turtle.left(90)
	turtle.forward(40)
	turtle.left(90)
	turtle.forward(40)
	turtle.left(90)
	turtle.forward(40)
	for contador in range(8%2==0):
		turtle.color('black')
		turtle.begin_fill()
		turtle.forward(40)
		turtle.left(90)
		turtle.forward(40)
		turtle.left(90)
		turtle.forward(40)
		turtle.left(90)
		turtle.forward(40)
		turtle.left(90)
		turtle.forward(40)
		turtle.end_fill()
turtle.right(90)
turtle.forward(40)
turtle.right(90)
for contador in range(4):
	turtle.forward(40)
	turtle.right(90)
	turtle.forward(40)
	turtle.right(90)
	turtle.forward(40)
	turtle.right(90)
	turtle.forward(40)
	turtle.right(90)
	turtle.forward(40)
	for contador in range(8%2==0):
		turtle.color('black')
		turtle.begin_fill()
		turtle.forward(40)
		turtle.right(90)
		turtle.forward(40)
		turtle.right(90)
		turtle.forward(40)
		turtle.right(90)
		turtle.forward(40)
		turtle.right(90)
		turtle.forward(40)
		turtle.end_fill()
turtle.left(90)
turtle.forward(40)
turtle.left(90)
for contador in range(4):
	turtle.forward(40)
	turtle.left(90)
	turtle.forward(40)
	turtle.left(90)
	turtle.forward(40)
	turtle.left(90)
	turtle.forward(40)
	turtle.left(90)
	turtle.forward(40)
	for contador in range(8%2==0):
		turtle.color('black')
		turtle.begin_fill()
		turtle.forward(40)
		turtle.left(90)
		turtle.forward(40)
		turtle.left(90)
		turtle.forward(40)
		turtle.left(90)
		turtle.forward(40)
		turtle.left(90)
		turtle.forward(40)
		turtle.end_fill()
turtle.right(90)
turtle.forward(40)
turtle.right(90)
for contador in range(4):
	turtle.forward(40)
	turtle.right(90)
	turtle.forward(40)
	turtle.right(90)
	turtle.forward(40)
	turtle.right(90)
	turtle.forward(40)
	turtle.right(90)
	turtle.forward(40)
	for contador in range(8%2==0):
		turtle.color('black')
		turtle.begin_fill()
		turtle.forward(40)
		turtle.right(90)
		turtle.forward(40)
		turtle.right(90)
		turtle.forward(40)
		turtle.right(90)
		turtle.forward(40)
		turtle.right(90)
		turtle.forward(40)
		turtle.end_fill()
turtle.left(90)
turtle.forward(40)
turtle.left(90)
for contador in range(4):
	turtle.forward(40)
	turtle.left(90)
	turtle.forward(40)
	turtle.left(90)
	turtle.forward(40)
	turtle.left(90)
	turtle.forward(40)
	turtle.left(90)
	turtle.forward(40)
	for contador in range(8%2==0):
		turtle.color('black')
		turtle.begin_fill()
		turtle.forward(40)
		turtle.left(90)
		turtle.forward(40)
		turtle.left(90)
		turtle.forward(40)
		turtle.left(90)
		turtle.forward(40)
		turtle.left(90)
		turtle.forward(40)
		turtle.end_fill()
turtle.right(90)
turtle.forward(40)
turtle.right(90)
for contador in range(4):
	turtle.forward(40)
	turtle.right(90)
	turtle.forward(40)
	turtle.right(90)
	turtle.forward(40)
	turtle.right(90)
	turtle.forward(40)
	turtle.right(90)
	turtle.forward(40)
	for contador in range(8%2==0):
		turtle.color('black')
		turtle.begin_fill()
		turtle.forward(40)
		turtle.right(90)
		turtle.forward(40)
		turtle.right(90)
		turtle.forward(40)
		turtle.right(90)
		turtle.forward(40)
		turtle.right(90)
		turtle.forward(40)
		turtle.end_fill()
turtle.penup()
turtle.right(90)
turtle.forward(300)
turtle.right(90)
turtle.forward(20)
turtle.color('red')
turtle.shape('circle')
turtle.stamp()
for contador in range(7):
	turtle.forward(40)
	turtle.color('red')
	turtle.shape('circle')
	turtle.stamp()
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.color('red')
turtle.shape('circle')
turtle.stamp()
for contador in range(7):
	turtle.forward(40)
	turtle.color('red')
	turtle.shape('circle')
	turtle.stamp()
turtle.left(90)
turtle.forward(200)
turtle.left(90)



	

	

	
	
turtle.exitonclick()